# Generated by Django 5.0 on 2024-02-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='username',
            options={'verbose_name': 'Username'},
        ),
    ]
